/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Persons {
  address: string | null;
  city: string | null;
  firstname: string | null;
  lastname: string | null;
  personid: number | null;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  password: string;
  updated_at: Timestamp | null;
}

export interface DB {
  persons: Persons;
  users: Users;
}
