name: Test Lint HMG

on:
  pull_request:
    branches:
      - homolog

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    strategy:
      matrix:
        node-version: [20.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn test
